export const jobs = [
  {
    id: 11234,
    title: "Front end developer",
    company_name: "Motion Recruitment",
    date: "2d",
    employment_type: "Full-time",
    development_type: "Front-end",
    experience_level: "Mid level",
    salary: "$80k-$100k",
    technologies: ["React"],
    description: "<p>Test content</p>",
    apply_link: "https://example.com",
    logo_url: "https://via.placeholder.com/150",
    company_site: "https://example.com",
  },
  {
    id: 11235,
    title: "Front end developer",
    company_name: "Motion Recruitment",
    date: "2d",
    employment_type: "Full-time",
    development_type: "Front-end",
    experience_level: "Mid level",
    salary: "$80k-$100k",
    technologies: ["React"],
    description: "<p>Test content</p>",
    apply_link: "https://example.com",
    logo_url: "https://via.placeholder.com/150",
    company_site: "https://example.com",
  },
  {
    id: 11236,
    title: "Front end developer",
    company_name: "Motion Recruitment",
    date: "2d",
    employment_type: "Full-time",
    development_type: "Front-end",
    experience_level: "Mid level",
    salary: "$80k-$100k",
    technologies: ["React"],
    description: "<p>Test content</p>",
    apply_link: "https://example.com",
    logo_url: "https://via.placeholder.com/150",
    company_site: "https://example.com",
  },
  {
    id: 11237,
    title: "Front end developer",
    company_name: "Motion Recruitment",
    date: "2d",
    employment_type: "Full-time",
    development_type: "Front-end",
    experience_level: "Mid level",
    salary: "$80k-$100k",
    technologies: ["React"],
    description: "<p>Test content</p>",
    apply_link: "https://example.com",
    logo_url: "https://via.placeholder.com/150",
    company_site: "https://example.com",
  },
  {
    id: 11238,
    title: "Front end developer",
    company_name: "Motion Recruitment",
    date: "2d",
    employment_type: "Full-time",
    development_type: "Front-end",
    experience_level: "Mid level",
    salary: "$80k-$100k",
    technologies: ["React"],
    description: "<p>Test content</p>",
    apply_link: "https://example.com",
    logo_url: "https://via.placeholder.com/150",
    company_site: "https://example.com",
  },
];

export const options = [
  "Employment type",
  "Development type",
  "Experience level",
  "Main technology",
  "Salary",
];
