

export const POST_DIR = 'posts';

export const GETTING_HIRED_PATH = 'getting-hired';
export const STANDING_OUT_PATH = 'standing-out';
export const DEMONSTRATING_COMPETENCE_PATH = 'demonstrating-competence';
export const HANDLING_OFFERS_PATH = 'handling-offers';


export const STANDING_OUT_PAGE_PATH = `/${GETTING_HIRED_PATH}/${STANDING_OUT_PATH}`;
export const DEMONSTRATING_COMPETENCE_PAGE_PATH = `/${GETTING_HIRED_PATH}/${DEMONSTRATING_COMPETENCE_PATH}`;
export const HANDLING_OFFERS_PAGE_PATH = `/${GETTING_HIRED_PATH}/${HANDLING_OFFERS_PATH}`;


export const STANDING_OUT_POSTS_PATH = `${POST_DIR}/${STANDING_OUT_PATH}`;
export const DEMONSTRATING_COMPETENCE_POSTS_PATH = `${POST_DIR}/${DEMONSTRATING_COMPETENCE_PATH}`;
export const HANDLING_OFFERS_POSTS_PATH = `${POST_DIR}/${HANDLING_OFFERS_PATH}`;



